name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Unit Tests and Coverage
      run: npm run coverage
    - name: Run Mutation Tests (Stryker)
      run: npm run test:mutation
    - name: Upload analysis reports
      uses: actions/upload-artifact@v4
      with:
        name: analysis-reports
        path: |
            coverage/
            stryker-output/

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
